a = [ {
	"biPrice" : 29.6,
	"commodityCateId" : 1,
	"commodityDesc" : "描述吧",
	"commodityId" : 1,
	"commodityName" : "天点农夫果园",
	"content" : "500ml",
	"dianBi" : 76.0,
	"enabled" : 1,
	"price" : 40.9,
	"specification" : "瓶",
	"stocks" : -30
}, {
	"biPrice" : 1.0,
	"commodityCateId" : 1,
	"commodityDesc" : "商品描述",
	"commodityId" : 3,
	"commodityName" : "今天5.18号",
	"content" : "500ml",
	"createTime" : 1526609975415,
	"dianBi" : 6.0,
	"enabled" : 1,
	"price" : 5.18,
	"specification" : "瓶",
	"stocks" : 327
}, {
	"biPrice" : 5.0,
	"commodityCateId" : 1,
	"commodityDesc" : "今天星期五",
	"commodityId" : 4,
	"commodityName" : "今天星期五",
	"content" : "500ml",
	"createTime" : 1526610243664,
	"dianBi" : 5.0,
	"enabled" : 1,
	"price" : 5.18,
	"specification" : "瓶",
	"stocks" : 532
}, {
	"biPrice" : 90.0,
	"commodityCateId" : 1,
	"commodityDesc" : "2想",
	"commodityId" : 6,
	"commodityName" : "我是天点人",
	"content" : "500ml",
	"dianBi" : 800.0,
	"enabled" : 1,
	"price" : 1000.0,
	"specification" : "你",
	"stocks" : 879
} ]
